table Bridge_L4L
	lineageTag: 1d509d5b-3359-432c-b055-d56b1a6c99d6

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: bdbeeb8f-cfe4-41d8-89b3-d1665f19585c
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreMonthKey
		dataType: string
		lineageTag: b8209002-022f-4568-8671-e62aa212774e
		summarizeBy: none
		sourceColumn: StoreMonthKey

		annotation SummarizationSetBy = Automatic

	column L4LKey
		dataType: double
		formatString: 0
		lineageTag: 88de615f-4cdd-4deb-b204-2c6760d47653
		summarizeBy: none
		sourceColumn: L4LKey

		annotation SummarizationSetBy = Automatic

	column L4LKey_PY
		dataType: double
		lineageTag: 88d064e9-a351-4306-ad4c-6fc175477438
		summarizeBy: sum
		sourceColumn: L4LKey_PY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: b8a14198-3086-4a3a-8c1b-2fa020f2d979
		summarizeBy: count
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column MonthKeyPY
		dataType: int64
		formatString: 0
		lineageTag: 4e714611-229f-4168-9830-91598bac432c
		summarizeBy: sum
		sourceColumn: MonthKeyPY

		annotation SummarizationSetBy = Automatic

	column FirstDayOfMonth
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6c78de6b-f535-4ec8-9ffb-c37e2cabd320
		summarizeBy: none
		sourceColumn: FirstDayOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastDayOfMonth
		dataType: dateTime
		formatString: Short Date
		lineageTag: 59fc3ec4-5f23-413f-bb15-3f7e7358f1de
		summarizeBy: none
		sourceColumn: LastDayOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FirstDayOfMonthPY
		dataType: dateTime
		formatString: Short Date
		lineageTag: e0b0e7f7-d058-49b8-9c48-8731c4fa5fcb
		summarizeBy: none
		sourceColumn: FirstDayOfMonthPY

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastDayOfMonthPY
		dataType: dateTime
		formatString: Short Date
		lineageTag: 59a39af5-a60d-431b-84f4-2a93cef82c3d
		summarizeBy: none
		sourceColumn: LastDayOfMonthPY

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OpenDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 81050b61-244a-4f56-96f2-ea9ea56fbd9a
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CloseDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 62a97c27-2d0b-4e8c-b2d9-45a233db1f9b
		summarizeBy: none
		sourceColumn: CloseDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Bridge_L4L = m
		mode: import
		source =
				let
				    Source = Store,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"StoreKey"}),
				    #"Added L4L_Months" = Table.AddColumn(#"Removed Other Columns", "L4L_Month", each L4L_Months),
				    #"Expanded L4L_Months" = Table.ExpandTableColumn(#"Added L4L_Months", "L4L_Month", {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}, {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded L4L_Months",{{"MonthKey", Int64.Type}, {"MonthKeyPY", Int64.Type}, {"FirstDayOfMonthPY", type date}, {"LastDayOfMonthPY", type date}, {"FirstDayOfMonth", type date}, {"LastDayOfMonth", type date}}),
				    #"Added StoreMonthKey" = Table.AddColumn(#"Changed Type", "StoreMonthKey", each Text.From([StoreKey]) & "_" & Text.From([MonthKey]), type text),
				    #"Merged L4L_Dates" = Table.NestedJoin(#"Added StoreMonthKey", {"StoreMonthKey"}, L4L_Dates, {"StoreMonthKey"}, "L4L_Dates", JoinKind.LeftOuter),
				    #"Expanded  L4L_Dates" = Table.ExpandTableColumn(#"Merged L4L_Dates", "L4L_Dates", {"CloseDate", "L4LKey", "L4LKey_PY", "OpenDate"}, {"CloseDate", "L4LKey", "L4LKey_PY", "OpenDate"}),
				    #"Replaced empty L4LKey with 1" = Table.ReplaceValue(#"Expanded  L4L_Dates",null,1,Replacer.ReplaceValue,{"L4LKey"}),
				    #"Replaced empty L4LKey_PY with 1" = Table.ReplaceValue(#"Replaced empty L4LKey with 1",null,1,Replacer.ReplaceValue,{"L4LKey_PY"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Replaced empty L4LKey_PY with 1",{"StoreKey", "MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY", "StoreMonthKey", "L4LKey", "L4LKey_PY", "OpenDate", "CloseDate"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

