table Bridge_L4L
	lineageTag: 1d509d5b-3359-432c-b055-d56b1a6c99d6

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: bdbeeb8f-cfe4-41d8-89b3-d1665f19585c
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreMonthKey
		dataType: string
		lineageTag: b8209002-022f-4568-8671-e62aa212774e
		summarizeBy: none
		sourceColumn: StoreMonthKey

		annotation SummarizationSetBy = Automatic

	column L4LKey
		dataType: int64
		formatString: 0
		lineageTag: 88de615f-4cdd-4deb-b204-2c6760d47653
		summarizeBy: none
		sourceColumn: L4LKey

		annotation SummarizationSetBy = Automatic

	partition Bridge_L4L = m
		mode: import
		source =
				let
				    Source = Store,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"StoreKey"}),
				    #"Added L4L_Months" = Table.AddColumn(#"Removed Other Columns", "L4L_Month", each L4L_Months),
				    #"Expanded L4L_Months" = Table.ExpandTableColumn(#"Added L4L_Months", "L4L_Month", {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}, {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded L4L_Months",{{"MonthKey", Int64.Type}, {"MonthKeyPY", Int64.Type}, {"FirstDayOfMonthPY", type date}, {"LastDayOfMonthPY", type date}, {"FirstDayOfMonth", type date}, {"LastDayOfMonth", type date}}),
				    #"Merged L4L_Dates" = Table.NestedJoin(#"Changed Type", {"StoreKey"}, L4L_Dates, {"StoreKey"}, "L4L_Dates", JoinKind.LeftOuter),
				    #"Expanded  L4L_Dates" = Table.ExpandTableColumn(#"Merged L4L_Dates", "L4L_Dates", {"StoreKey", "GeographyKey", "OpenDate", "CloseDate", "OpenDate_EOM", "CloseDate_EOM", "L4L_Status_Src"}, {"StoreKey_L4L", "GeographyKey", "OpenDate", "CloseDate", "OpenDate_EOM", "CloseDate_EOM", "L4L_Status_Src"}),
				    #"Added YearDiff_Open" = Table.AddColumn(#"Expanded  L4L_Dates", "YearDiff_Open", each Date.Year([LastDayOfMonth]) - Date.Year([OpenDate]), Int64.Type),
				    #"Added YearDiff_Close" = Table.AddColumn(#"Added YearDiff_Open", "YearDiff_Close", each Date.Year([LastDayOfMonth]) - Date.Year([CloseDate]), Int64.Type),
				    #"Added L4L_Status_Int" = Table.AddColumn(#"Added YearDiff_Close", "L4L_Status_Int", each if [StoreKey_L4L] = null then 1
				else if [YearDiff_Open] = 1 or [YearDiff_Close] = 1 then [L4L_Status_Src]
				else 1),
				    #"Added L4LKey" = Table.AddColumn(#"Added L4L_Status_Int", "L4LKey", each if [L4L_Status_Int] = 2
				and [FirstDayOfMonthPY] <= [OpenDate]
				then 2
				else if [L4L_Status_Int] = 3
				and [LastDayOfMonthPY] >= [CloseDate]
				then 3
				else if [L4L_Status_Int] = 4
				and ([LastDayOfMonthPY] >= [CloseDate] and [FirstDayOfMonthPY] <= [OpenDate])
				then 4
				else 1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added L4LKey",{{"L4LKey", Int64.Type}}),
				    #"Added StoreMonthKey" = Table.AddColumn(#"Changed Type1", "StoreMonthKey", each Text.From([StoreKey]) & "_" & Text.From([MonthKey]), type text),
				    #"Removed unneeded columns" = Table.SelectColumns(#"Added StoreMonthKey",{"StoreKey", "L4LKey", "StoreMonthKey"})
				in
				    #"Removed unneeded columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

