table Bridge_L4L
	lineageTag: 1d509d5b-3359-432c-b055-d56b1a6c99d6

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: bdbeeb8f-cfe4-41d8-89b3-d1665f19585c
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreMonthKey
		dataType: string
		lineageTag: b8209002-022f-4568-8671-e62aa212774e
		summarizeBy: none
		sourceColumn: StoreMonthKey

		annotation SummarizationSetBy = Automatic

	column L4LKey
		dataType: int64
		formatString: 0
		lineageTag: 88de615f-4cdd-4deb-b204-2c6760d47653
		summarizeBy: none
		sourceColumn: L4LKey

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: 5949b48d-87f3-4184-bc24-b117110691a6
		summarizeBy: count
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column MonthKeyPY
		dataType: int64
		formatString: 0
		lineageTag: 458c9bc0-f75f-4cc2-a98a-38e7045b50b1
		summarizeBy: sum
		sourceColumn: MonthKeyPY

		annotation SummarizationSetBy = Automatic

	column FirstDayOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8527dc9f-c633-4c64-86de-8a4aa1b549ea
		summarizeBy: none
		sourceColumn: FirstDayOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastDayOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5111b3f5-0804-4e07-82ce-cbcf5b924d4a
		summarizeBy: none
		sourceColumn: LastDayOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FirstDayOfMonthPY
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e8ffd72-ee19-47f4-ab30-fd2dffbe3273
		summarizeBy: none
		sourceColumn: FirstDayOfMonthPY

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastDayOfMonthPY
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2a3c5f2-bcb2-425b-92ff-619c5d9f0055
		summarizeBy: none
		sourceColumn: LastDayOfMonthPY

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StoreKey_L4L
		dataType: int64
		formatString: 0
		lineageTag: 0e91f1ea-cb2f-4c2f-a5c7-630b04d0456a
		summarizeBy: sum
		sourceColumn: StoreKey_L4L

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: string
		lineageTag: 4812c936-9413-40fe-9d88-461a0046bf7a
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 800a118f-17d3-407d-8346-aa01bd5c0208
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CloseDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 07fa36d7-e346-48f7-b842-ece1db865fac
		summarizeBy: none
		sourceColumn: CloseDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OpenDate_EOM
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8897d517-a00a-414a-be55-29504352d21a
		summarizeBy: none
		sourceColumn: OpenDate_EOM

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CloseDate_EOM
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1f19867-fd4c-4da6-9f71-67a93b230d32
		summarizeBy: none
		sourceColumn: CloseDate_EOM

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column L4L_Status_Src
		dataType: int64
		formatString: 0
		lineageTag: 40a4f85d-ee60-45ec-aa8b-2864ffa92cee
		summarizeBy: sum
		sourceColumn: L4L_Status_Src

		annotation SummarizationSetBy = Automatic

	column YearDiff_Open
		dataType: int64
		formatString: 0
		lineageTag: a97f3e75-92e6-4f7a-8740-86f0c90cb4d9
		summarizeBy: sum
		sourceColumn: YearDiff_Open

		annotation SummarizationSetBy = Automatic

	column YearDiff_Close
		dataType: int64
		formatString: 0
		lineageTag: 68b3cadc-0b73-4454-883e-723c0a1c98d4
		summarizeBy: sum
		sourceColumn: YearDiff_Close

		annotation SummarizationSetBy = Automatic

	column L4L_Status_Int
		dataType: string
		lineageTag: 7bff00fb-90a1-4002-ab89-5744dc1e2d4f
		summarizeBy: none
		sourceColumn: L4L_Status_Int

		annotation SummarizationSetBy = Automatic

	column L4L_Check
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0689457-e6a1-4868-8e36-f59313d38991
		summarizeBy: none
		sourceColumn: L4L_Check

		annotation SummarizationSetBy = Automatic

	partition Bridge_L4L = m
		mode: import
		source =
				let
				    Source = Store,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"StoreKey"}),
				    #"Added L4L_Months" = Table.AddColumn(#"Removed Other Columns", "L4L_Month", each L4L_Months),
				    #"Expanded L4L_Months" = Table.ExpandTableColumn(#"Added L4L_Months", "L4L_Month", {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}, {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded L4L_Months",{{"MonthKey", Int64.Type}, {"MonthKeyPY", Int64.Type}, {"FirstDayOfMonthPY", type date}, {"LastDayOfMonthPY", type date}, {"FirstDayOfMonth", type date}, {"LastDayOfMonth", type date}}),
				    #"Added StoreMonthKey" = Table.AddColumn(#"Changed Type", "StoreMonthKey", each Text.From([StoreKey]) & "_" & Text.From([MonthKey]), type text),
				    #"Merged L4L_Dates" = Table.NestedJoin(#"Added StoreMonthKey", {"StoreKey"}, L4L_Dates, {"StoreKey"}, "L4L_Dates", JoinKind.LeftOuter),
				    #"Expanded  L4L_Dates" = Table.ExpandTableColumn(#"Merged L4L_Dates", "L4L_Dates", {"StoreKey", "GeographyKey", "OpenDate", "CloseDate", "OpenDate_EOM", "CloseDate_EOM", "L4L_Status_Src"}, {"StoreKey_L4L", "GeographyKey", "OpenDate", "CloseDate", "OpenDate_EOM", "CloseDate_EOM", "L4L_Status_Src"}),
				    #"Added YearDiff_Open" = Table.AddColumn(#"Expanded  L4L_Dates", "YearDiff_Open", each Date.Year([LastDayOfMonth]) - Date.Year([OpenDate]), Int64.Type),
				    #"Added YearDiff_Close" = Table.AddColumn(#"Added YearDiff_Open", "YearDiff_Close", each Date.Year([LastDayOfMonth]) - Date.Year([CloseDate]), Int64.Type),
				    #"Added L4L_Status_Int" = Table.AddColumn(#"Added YearDiff_Close", "L4L_Status_Int", each if [StoreKey_L4L] = null then 1
				else if [YearDiff_Open] = 1 or [YearDiff_Close] = 1 then [L4L_Status_Src]
				else 1),
				    #"Added L4LKey" = Table.AddColumn(#"Added L4L_Status_Int", "L4LKey", each if [L4L_Status_Int] = 2
				and [FirstDayOfMonthPY] <= [OpenDate]
				then 2
				else if [L4L_Status_Int] = 3
				and [LastDayOfMonthPY] >= [CloseDate]
				then 3
				else if [L4L_Status_Int] = 4
				and ([LastDayOfMonthPY] >= [CloseDate] and [FirstDayOfMonthPY] <= [OpenDate])
				then 4
				else 1),
				    #"Added L4L_Check" = Table.AddColumn(#"Added L4LKey", "L4L_Check", each if [L4L_Status_Src] = null or [L4L_Status_Src] = 1
				   or ([L4L_Status_Src] <> 1 and ([YearDiff_Open] = 1
				   or [YearDiff_Close] = 1 ))
				   then true
				   else false, type logical),
				    #"Removev L4L_Check = FALSE" = Table.SelectRows(#"Added L4L_Check", each ([L4L_Check] = true)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removev L4L_Check = FALSE",{{"L4LKey", Int64.Type}}),
				    //#"Removed unneeded columns" = Table.SelectColumns(#"Added StoreMonthKey",{"StoreKey", "L4LKey", "StoreMonthKey"}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type1")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

