table Bridge_L4L
	lineageTag: 1d509d5b-3359-432c-b055-d56b1a6c99d6

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: bdbeeb8f-cfe4-41d8-89b3-d1665f19585c
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreMonthKey
		dataType: string
		lineageTag: b8209002-022f-4568-8671-e62aa212774e
		summarizeBy: none
		sourceColumn: StoreMonthKey

		annotation SummarizationSetBy = Automatic

	column L4LKey
		dataType: int64
		formatString: 0
		lineageTag: 88de615f-4cdd-4deb-b204-2c6760d47653
		summarizeBy: none
		sourceColumn: L4LKey

		annotation SummarizationSetBy = Automatic

	partition Bridge_L4L = m
		mode: import
		source =
				let
				    Source = Store,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"StoreKey"}),
				    #"Added L4L_Months" = Table.AddColumn(#"Removed Other Columns", "L4L_Month", each L4L_Months),
				    #"Expanded L4L_Months" = Table.ExpandTableColumn(#"Added L4L_Months", "L4L_Month", {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}, {"MonthKey", "MonthKeyPY", "FirstDayOfMonth", "LastDayOfMonth", "FirstDayOfMonthPY", "LastDayOfMonthPY"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded L4L_Months",{{"MonthKey", Int64.Type}, {"MonthKeyPY", Int64.Type}, {"FirstDayOfMonthPY", type date}, {"LastDayOfMonthPY", type date}, {"FirstDayOfMonth", type date}, {"LastDayOfMonth", type date}}),
				    #"Added StoreMonthKey" = Table.AddColumn(#"Changed Type", "StoreMonthKey", each Text.From([StoreKey]) & "_" & Text.From([MonthKey]), type text),
				    #"Merged L4L_Dates" = Table.NestedJoin(#"Added StoreMonthKey", {"StoreKey"}, L4L_Dates, {"StoreKey"}, "L4L_Dates", JoinKind.LeftOuter),
				    #"Expanded  L4L_Dates" = Table.ExpandTableColumn(#"Merged L4L_Dates", "L4L_Dates", {"StoreKey", "OpenDate", "CloseDate", "L4L_Status_Src"}, {"StoreKey_L4L", "OpenDate", "CloseDate", "L4L_Status_Src"}),
				    #"Added YearDiff_Open" = Table.AddColumn(#"Expanded  L4L_Dates", "YearDiff_Open", each Date.Year([LastDayOfMonth]) - Date.Year([OpenDate]), Int64.Type),
				    #"Added YearDiff_Close" = Table.AddColumn(#"Added YearDiff_Open", "YearDiff_Close", each Date.Year([LastDayOfMonth]) - Date.Year([CloseDate]), Int64.Type),
				    #"Added L4L_Status_Int" = Table.AddColumn(#"Added YearDiff_Close", "L4L_Status_Int", each if [StoreKey_L4L] = null then 1
				else if [YearDiff_Open] = 1 or [YearDiff_Close] = 1 then [L4L_Status_Src]
				else 1),
				    #"Added OpenDate_Corr" = Table.AddColumn(#"Added L4L_Status_Int", "OpenDate_Corr", each if [YearDiff_Open] <> 1 then [FirstDayOfMonth] else [OpenDate], type date),
				    #"Added CloseDate_Corr" = Table.AddColumn(#"Added OpenDate_Corr", "CloseDate_Corr", each if [YearDiff_Close] <> 1 then [LastDayOfMonth] else [CloseDate], type date),
				    #"Removed Original Open and Closed Dates" = Table.RemoveColumns(#"Added CloseDate_Corr",{"OpenDate", "CloseDate"}),
				    #"Renamed Corr Columns" = Table.RenameColumns(#"Removed Original Open and Closed Dates",{{"OpenDate_Corr", "OpenDate"}, {"CloseDate_Corr", "CloseDate"}}),
				    #"Added L4LKey" = Table.AddColumn(#"Renamed Corr Columns", "L4LKey", each if [L4L_Status_Int] = 2
				and [FirstDayOfMonthPY] <= [OpenDate]
				then 2
				else if [L4L_Status_Int] = 3
				and [LastDayOfMonthPY] >= [CloseDate]
				then 3
				else if [L4L_Status_Int] = 4
				and ([LastDayOfMonthPY] >= [CloseDate] and [FirstDayOfMonthPY] <= [OpenDate])
				then 4
				else 1),
				    #"Added L4L_Check" = Table.AddColumn(#"Added L4LKey", "L4L_Check", each if [L4L_Status_Src] = null or [L4L_Status_Src] = 1
				   then true
				   else if ([L4L_Status_Src] <> 1 and ([YearDiff_Open] = 1
				   or [YearDiff_Close] = 1 ))
				   then true
				   else false),
				    #"Removed L4L_Check = FALSE" = Table.SelectRows(#"Added L4L_Check", each ([L4L_Check] = true)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed L4L_Check = FALSE",{{"L4LKey", Int64.Type}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Changed Type1",{"StoreKey", "StoreMonthKey", "L4LKey"})
				in
				    #"Removed Other Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

