table 'Exchange Rate'
	lineageTag: 6c25e9bf-6912-469e-93a0-a47876b28652

	measure 'Average Rate' = AVERAGE('Exchange Rate'[Average_Rate])
		formatString: 0.00000
		lineageTag: e4a1c406-e89f-4c81-8a6d-71f3fa75d068

	measure 'End Of Day Rate' = AVERAGE('Exchange Rate'[EndOfDay_Rate])
		lineageTag: d082cbd3-6745-4ff9-8beb-46aca40d05b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurrencyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d30629b0-e2b6-4712-a376-e15deaf39202
		summarizeBy: none
		sourceColumn: CurrencyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		isHidden
		formatString: dd-mmm-yy
		lineageTag: caa11403-81fa-4f8d-9cf5-0f98424e86e0
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Average_Rate
		dataType: double
		isHidden
		formatString: 0.00000
		lineageTag: bbd58a8a-fa13-4669-9c1c-535883b85ac0
		summarizeBy: average
		sourceColumn: Average_Rate

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column EndOfDay_Rate
		dataType: double
		isHidden
		lineageTag: ce8c4e51-66e3-4ead-b6cf-8bee27949bf9
		summarizeBy: average
		sourceColumn: EndOfDay_Rate

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExchangeRateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2f547572-9cb6-480c-979c-86b6d2ca9bb6
		summarizeBy: count
		sourceColumn: ExchangeRateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ETLLoadID
		dataType: int64
		formatString: 0
		lineageTag: 2b251695-bf72-4853-9d7b-6b6649416d28
		summarizeBy: count
		sourceColumn: ETLLoadID

		annotation SummarizationSetBy = Automatic

	column LoadDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 56207af9-0f5e-4a3a-a355-e91ffa651976
		summarizeBy: none
		sourceColumn: LoadDate

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9baf0381-10ed-4027-ac19-80329bc92867
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

	partition 'Exchange Rate-6c8b71cd-95b1-4c0d-9ce8-7c38fb4b4835' = m
		mode: import
		source =
				let
				    Source = Sql.Database(SourceServer, ContosoRetailDW_DB),
				    dbo_FactExchangeRate = Source{[Schema="dbo",Item="FactExchangeRate"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_FactExchangeRate,{{"EndOfDayRate", "EndOfDay_Rate"}, {"AverageRate", "Average_Rate"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

