SELECT [SalesKey]
        ,[SaleLineCounter]    AS  [Sale Line Counter]
        ,CONVERT(date, DATEADD(yyyy, 16, [DateKey]))     AS  [DateKey]
        ,[channelKey]
        ,[StoreKey]
        ,[ProductKey]
        ,[PromotionKey]
        ,[CurrencyKey]
        ,[UnitCost]
        ,[UnitPrice]
        ,[SalesQuantity]
        ,[ReturnQuantity]
        ,[ReturnAmount]
        ,[DiscountQuantity]
        ,[DiscountAmount]
        ,[TotalCost]
        ,[SalesAmount]
        ,[DateKeyYear]
    FROM [dbo].[v_FactSales];
